// <auto-generated />
namespace SbmsWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class lookup_Add_New : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lookup_Add_New));
        
        string IMigrationMetadata.Id
        {
            get { return "201904191639373_lookup_Add_New"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
